def configure(conf):
    conf.env.append_value('DEFINES', 'BT_REQUIRE_EARLY_BONDINGS')


def build(bld):
    excludes = []
    if not bld.is_obelix() or not bld.env.IS_MFG:
        excludes.extend(['gh3x2x_tuning_service.c'])

    driver_source = bld.path.ant_glob(['*.c'], excl=excludes)

    bld.objects(
        source=driver_source,
        target='bt_driver',
        use=[
          'nimble',
          'freertos',
          'fw_includes',
          'pbl_includes',
        ],
    )
