/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */


#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

static const ResourceVersion SYSTEM_RESOURCE_VERSION = {
  .crc = 3130967296,
  .timestamp = 0
};
