# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'get_bytes.c',
        'get_bytes_storage.c',
        'get_bytes_storage_coredump.c',
        'get_bytes_storage_file.c',
        'get_bytes_storage_flash.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_common_get_bytes',
    )

    bld.env.SERVICES.append('services_common_get_bytes')
