/* SPDX-FileCopyrightText: 2026 Core Devices LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#define PAGE_SIZE_BYTES (0x100)

#define SECTOR_SIZE_BYTES (0x10000)
#define SECTOR_ADDR_MASK (~(SECTOR_SIZE_BYTES - 1))

#define SUBSECTOR_SIZE_BYTES (0x1000)
#define SUBSECTOR_ADDR_MASK (~(SUBSECTOR_SIZE_BYTES - 1))

#define FLASH_REGION_BASE_ADDRESS 0x10000000

#define FLASH_REGION_DEF(MACRO, arg)                                                        \
  MACRO(PTABLE,                  0x0010000 /*    64K */, arg) /* 0x10000000 - 0x1000FFFF */ \
  MACRO(BOOTLOADER,              0x0010000 /*    64K */, arg) /* 0x10010000 - 0x1001FFFF */ \
  MACRO(FIRMWARE_SLOT_0,         0x0300000 /*  3072K */, arg) /* 0x10020000 - 0x1031FFFF */ \
  MACRO(FIRMWARE_SLOT_1,         0x0300000 /*  3072K */, arg) /* 0x10320000 - 0x1061FFFF */ \
  MACRO(SYSTEM_RESOURCES_BANK_0, 0x0200000 /*  2048K */, arg) /* 0x10620000 - 0x1081FFFF */ \
  MACRO(SYSTEM_RESOURCES_BANK_1, 0x0200000 /*  2048K */, arg) /* 0x10820000 - 0x10A1FFFF */ \
  MACRO(SAFE_FIRMWARE,           0x0080000 /*   512K */, arg) /* 0x10A20000 - 0x10A9FFFF */ \
  MACRO(FILESYSTEM,              0x0520000 /*  5248K */, arg) /* 0x10AA0000 - 0x10FBFFFF */ \
  MACRO(RSVD1,                   0x000F000 /*    60K */, arg) /* 0x10FC0000 - 0x10FCEFFF */ \
  MACRO(DEBUG_DB,                0x0020000 /*   128K */, arg) /* 0x10FCF000 - 0x10FEEFFF */ \
  MACRO(RSVD2,                   0x000F000 /*    60K */, arg) /* 0x10FEF000 - 0x10FFDFFF */ \
  MACRO(MFG_INFO,                0x0001000 /*     4K */, arg) /* 0x10FFE000 - 0x10FFEFFF */ \
  MACRO(SHARED_PRF_STORAGE,      0x0001000 /*     4K */, arg) /* 0x10FFF000 - 0x10FFFFFF */

#include "flash_region_def_helper.h"

#define FLASH_REGION_PTABLE_BEGIN FLASH_REGION_START_ADDR(PTABLE)
#define FLASH_REGION_PTABLE_END FLASH_REGION_END_ADDR(PTABLE)

#define FLASH_REGION_BOOTLOADER_BEGIN FLASH_REGION_START_ADDR(BOOTLOADER)
#define FLASH_REGION_BOOTLOADER_END FLASH_REGION_END_ADDR(BOOTLOADER)

#define FLASH_REGION_FIRMWARE_SLOT_0_BEGIN FLASH_REGION_START_ADDR(FIRMWARE_SLOT_0)
#define FLASH_REGION_FIRMWARE_SLOT_0_END FLASH_REGION_END_ADDR(FIRMWARE_SLOT_0)

#define FLASH_REGION_FIRMWARE_SLOT_1_BEGIN FLASH_REGION_START_ADDR(FIRMWARE_SLOT_1)
#define FLASH_REGION_FIRMWARE_SLOT_1_END FLASH_REGION_END_ADDR(FIRMWARE_SLOT_1)

#define FLASH_REGION_SYSTEM_RESOURCES_BANK_0_BEGIN FLASH_REGION_START_ADDR(SYSTEM_RESOURCES_BANK_0)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_0_END FLASH_REGION_END_ADDR(SYSTEM_RESOURCES_BANK_0)

#define FLASH_REGION_SYSTEM_RESOURCES_BANK_1_BEGIN FLASH_REGION_START_ADDR(SYSTEM_RESOURCES_BANK_1)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_1_END FLASH_REGION_END_ADDR(SYSTEM_RESOURCES_BANK_1)

#define FLASH_REGION_SAFE_FIRMWARE_BEGIN FLASH_REGION_START_ADDR(SAFE_FIRMWARE)
#define FLASH_REGION_SAFE_FIRMWARE_END FLASH_REGION_END_ADDR(SAFE_FIRMWARE)

#define FLASH_REGION_FILESYSTEM_BEGIN FLASH_REGION_START_ADDR(FILESYSTEM)
#define FLASH_REGION_FILESYSTEM_END FLASH_REGION_END_ADDR(FILESYSTEM)
#define FLASH_FILESYSTEM_BLOCK_SIZE SUBSECTOR_SIZE_BYTES

#define FLASH_REGION_DEBUG_DB_BEGIN FLASH_REGION_START_ADDR(DEBUG_DB)
#define FLASH_REGION_DEBUG_DB_END FLASH_REGION_END_ADDR(DEBUG_DB)
#define FLASH_DEBUG_DB_BLOCK_SIZE SUBSECTOR_SIZE_BYTES

#define FLASH_REGION_MFG_INFO_BEGIN FLASH_REGION_START_ADDR(MFG_INFO)
#define FLASH_REGION_MFG_INFO_END FLASH_REGION_END_ADDR(MFG_INFO)

#define FLASH_REGION_SHARED_PRF_STORAGE_BEGIN FLASH_REGION_START_ADDR(SHARED_PRF_STORAGE)
#define FLASH_REGION_SHARED_PRF_STORAGE_END FLASH_REGION_END_ADDR(SHARED_PRF_STORAGE)

#define BOARD_NOR_FLASH_SIZE (FLASH_REGION_START_ADDR(_COUNT) - FLASH_REGION_BASE_ADDRESS)

FLASH_REGION_SIZE_CHECK(SUBSECTOR_SIZE_BYTES)
_Static_assert(BOARD_NOR_FLASH_SIZE == 0x1000000, "Flash size should be 16mb");
