from resources.types.resource_definition import ResourceDefinition
from resources.types.resource_object import ResourceObject

def configure(conf):
    pass


def build(bld):
    sources = bld.path.ant_glob('**/*.c')
    bld.stlib(source=sources,
              target='bt_driver',
              use=[
                'fw_includes',
                'freertos',
                'pbl_includes',
              ])


# vim:filetype=python
