# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    conf.recurse('analytics')
    conf.recurse('battery')
    conf.recurse('bluetooth')
    conf.recurse('comm_session')
    conf.recurse('compositor')
    conf.recurse('get_bytes')
    conf.recurse('hrm')
    conf.recurse('i18n')
    conf.recurse('new_timer')
    conf.recurse('put_bytes')
    conf.recurse('shared_prf_storage')
    conf.recurse('touch')


def build(bld):
    bld.recurse('analytics')
    bld.recurse('battery')
    bld.recurse('bluetooth')
    bld.recurse('comm_session')
    bld.recurse('compositor')
    bld.recurse('get_bytes')
    bld.recurse('hrm')
    bld.recurse('i18n')
    bld.recurse('new_timer')
    bld.recurse('put_bytes')
    bld.recurse('shared_prf_storage')
    if bld.capability('HAS_TOUCHSCREEN'):
        bld.recurse('touch')
