# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'dls_command.c',
        'dls_endpoint.c',
        'dls_list.c',
        'dls_main.c',
        'dls_storage.c',
        'dls_syscalls.c',
    ]

    bld.stlib(
        use=['fw_includes', 'services_common_analytics'],
        source=sources,
        target='services_normal_data_logging',
    )

    bld.env.SERVICES.append('services_normal_data_logging')
