# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'protobuf_log.c',
        'protobuf_log_activity_sessions.c',
        'protobuf_log_hr.c',
        'protobuf_log_test.c',
        'protobuf_log_util.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_normal_protobuf_log',
    )

    bld.env.SERVICES.append('services_normal_protobuf_log')
