# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'alarm.c',
        'alarm_pin.c',
    ]

    bld.stlib(
        use=['fw_includes', 'services_common_analytics'],
        source=sources,
        target='services_normal_alarms',
    )

    bld.env.SERVICES.append('services_normal_alarms')
