/*
 * Minimal Pico SDK board header for the Adafruit Fruit Jam RP2350B.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// pico_cmake_set PICO_PLATFORM=rp2350

#ifndef _BOARDS_FRUITJAM_RP2350_H
#define _BOARDS_FRUITJAM_RP2350_H

#ifndef PICO_XOSC_STARTUP_DELAY_MULTIPLIER
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64
#endif

#define FRUITJAM_RP2350

// RP2350B, needed for GPIOs 30-47.
#define PICO_RP2350A 0

#define FRUITJAM_A0_PIN 40
#define FRUITJAM_A1_PIN 41
#define FRUITJAM_A2_PIN 42
#define FRUITJAM_A3_PIN 43
#define FRUITJAM_A4_PIN 44
#define FRUITJAM_A5_PIN 45
#define FRUITJAM_D6_PIN 6
#define FRUITJAM_D7_PIN 7
#define FRUITJAM_D8_PIN 8
#define FRUITJAM_D9_PIN 9
#define FRUITJAM_D10_PIN 10

#define FRUITJAM_WIFI_SCK_PIN 30
#define FRUITJAM_WIFI_MOSI_PIN 31
#define FRUITJAM_WIFI_MISO_PIN 28
#define FRUITJAM_WIFI_CS_PIN 46

#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 1
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 8
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 9
#endif

#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN 29
#endif
#ifndef PICO_DEFAULT_WS2812_PIN
#define PICO_DEFAULT_WS2812_PIN 32
#endif

#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 0
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 20
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 21
#endif

#ifndef PICO_DEFAULT_SPI
#define PICO_DEFAULT_SPI 1
#endif
#ifndef PICO_DEFAULT_SPI_SCK_PIN
#define PICO_DEFAULT_SPI_SCK_PIN FRUITJAM_WIFI_SCK_PIN
#endif
#ifndef PICO_DEFAULT_SPI_TX_PIN
#define PICO_DEFAULT_SPI_TX_PIN FRUITJAM_WIFI_MOSI_PIN
#endif
#ifndef PICO_DEFAULT_SPI_RX_PIN
#define PICO_DEFAULT_SPI_RX_PIN FRUITJAM_WIFI_MISO_PIN
#endif
#ifndef PICO_DEFAULT_SPI_CSN_PIN
#define PICO_DEFAULT_SPI_CSN_PIN FRUITJAM_WIFI_CS_PIN
#endif

#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1

#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif

// pico_cmake_set_default PICO_FLASH_SIZE_BYTES = (16 * 1024 * 1024)
#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif

// pico_cmake_set_default PICO_RP2350_A2_SUPPORTED = 1
#ifndef PICO_RP2350_A2_SUPPORTED
#define PICO_RP2350_A2_SUPPORTED 1
#endif

#endif
