from waftools.pebble_test import clar

def build(ctx):
    clar(ctx,
         sources_ant_glob = "src/fw/mfg/mfg_serials.c tests/fakes/fake_otp.c",
         test_sources_ant_glob = "test_mfg_serials.c",
         override_includes=['dummy_board'],
         platforms=['obelix'])

# vim:filetype=python

