#ifndef PICO2_W_CYW43_HCI_PROBE_LWIPOPTS_H
#define PICO2_W_CYW43_HCI_PROBE_LWIPOPTS_H

#define NO_SYS 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_NETCONN 0
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_RAW 1
#define LWIP_SOCKET 0

#endif
