# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'app_order_storage.c',
        'app_storage.c',
        'process_commands.c',
        'process_loader_storage.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_normal_process_management',
    )

    bld.env.SERVICES.append('services_normal_process_management')
