/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include <stdint.h>
#include <stdbool.h>

//! @param rand_out Storage for the 32-bit random number generated by the STM32
//! @return True if a random number was succesfully generated
bool rng_rand(uint32_t *rand_out);
