# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'app_message_receiver.c',
        'app_message_sender.c',
    ]

    bld.stlib(
        use=['fw_includes', 'services_common_analytics'],
        source=sources,
        target='services_normal_app_message',
    )

    bld.env.SERVICES.append('services_normal_app_message')
