/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#define DISPLAY_ORIENTATION_COLUMN_MAJOR_INVERTED 1
#define DISPLAY_ORIENTATION_ROTATED_180 0
#define DISPLAY_ORIENTATION_ROW_MAJOR 0
#define DISPLAY_ORIENTATION_ROW_MAJOR_INVERTED 0

#define PBL_BW 0
#define PBL_COLOR 1

#define PBL_RECT 1
#define PBL_ROUND 0

#define PBL_DISPLAY_WIDTH 144
#define PBL_DISPLAY_HEIGHT 168

#define LEGACY_2X_DISP_COLS DISP_COLS
#define LEGACY_2X_DISP_ROWS DISP_ROWS
#define LEGACY_3X_DISP_COLS DISP_COLS
#define LEGACY_3X_DISP_ROWS DISP_ROWS

#define DISPLAY_FRAMEBUFFER_BYTES (PBL_DISPLAY_WIDTH * PBL_DISPLAY_HEIGHT)
