from waflib.Configure import ConfigurationContext, conf

@conf
def get_board(ctx):
    if isinstance(ctx, ConfigurationContext):
        return ctx.options.board
    else:
        return ctx.env.BOARD

# Platform specific predicates

@conf
def is_asterix(ctx):
    return ctx.get_board().startswith('asterix')

@conf
def is_obelix(ctx):
    return ctx.get_board().startswith('obelix')

@conf
def is_getafix(ctx):
    return ctx.get_board().startswith('getafix')

@conf
def is_qemu_emery(ctx):
    return ctx.get_board() == 'qemu_emery'

@conf
def is_qemu_flint(ctx):
    return ctx.get_board() == 'qemu_flint'

@conf
def is_qemu_gabbro(ctx):
    return ctx.get_board() == 'qemu_gabbro'

@conf
def get_platform_name(ctx):
    if is_qemu_emery(ctx):
        return "qemu_emery"
    elif is_qemu_flint(ctx):
        return "qemu_flint"
    elif is_qemu_gabbro(ctx):
        return "qemu_gabbro"
    elif is_asterix(ctx):
        return "asterix"
    elif is_obelix(ctx):
        return "obelix"
    elif is_getafix(ctx):
        return "getafix"
    else:
        return "unknown"


# Platform features

@conf
def get_qemu_machine(ctx):
    if is_qemu_emery(ctx):
        return 'pebble-emery'
    elif is_qemu_flint(ctx):
        return 'pebble-flint'
    elif is_qemu_gabbro(ctx):
        return 'pebble-gabbro'
    else:
        return 'unknown'

# Build

def configure(ctx):
    pass


def build(ctx):
    pass


# vim:filetype=python
