from waflib.Configure import ConfigurationContext, conf

@conf
def get_board(ctx):
    if isinstance(ctx, ConfigurationContext):
        return ctx.options.board
    else:
        return ctx.env.BOARD

@conf
def is_bigboard(ctx):
    return '_bb' in ctx.get_board()


# Platform specific predicates

@conf
def is_asterix(ctx):
    return ctx.get_board().startswith('asterix')

@conf
def is_obelix(ctx):
    return ctx.get_board().startswith('obelix')

@conf
def is_getafix(ctx):
    return ctx.get_board().startswith('getafix')

@conf
def is_qemu_emery(ctx):
    return ctx.get_board() == 'qemu_emery'

@conf
def is_qemu_flint(ctx):
    return ctx.get_board() == 'qemu_flint'

@conf
def is_qemu_gabbro(ctx):
    return ctx.get_board() == 'qemu_gabbro'

@conf
def get_platform_name(ctx):
    if is_qemu_emery(ctx):
        return "qemu_emery"
    elif is_qemu_flint(ctx):
        return "qemu_flint"
    elif is_qemu_gabbro(ctx):
        return "qemu_gabbro"
    elif is_asterix(ctx):
        return "asterix"
    elif is_obelix(ctx):
        return "obelix"
    elif is_getafix(ctx):
        return "getafix"
    else:
        return "unknown"


# Platform features

@conf
def get_qemu_machine(ctx):
    if is_qemu_emery(ctx):
        return 'pebble-emery'
    elif is_qemu_flint(ctx):
        return 'pebble-flint'
    elif is_qemu_gabbro(ctx):
        return 'pebble-gabbro'
    else:
        return 'unknown'


@conf
def get_qemu_cpu(ctx):
    if is_qemu_emery(ctx):
        return 'cortex-m33'
    elif is_qemu_flint(ctx):
        return 'cortex-m4'
    elif is_qemu_gabbro(ctx):
        return 'cortex-m33'
    elif is_asterix(ctx):
        return 'cortex-m4'
    else:
        return 'unknown'


@conf
def get_qemu_spi_flash_args(ctx, spi_flash_path):
    if ctx.env.CONFIG_QEMU:
        return ['-drive', 'if=mtd,format=raw,file={}'.format(spi_flash_path)]
    else:
        return None

@conf
def add_platform_defines(ctx, env):
    if ctx.is_qemu_emery():
        platform = 'QEMU_EMERY'
    elif ctx.is_qemu_flint():
        platform = 'QEMU_FLINT'
    elif ctx.is_qemu_gabbro():
        platform = 'QEMU_GABBRO'
    elif ctx.is_asterix():
        platform = 'ASTERIX'
    elif ctx.is_obelix():
        platform = 'OBELIX'
    elif ctx.is_getafix():
        platform = 'GETAFIX'
    else:
        ctx.fatal('No platform specified for {}!'.format(ctx.options.board))

    defines = ['BOARD_{}=1'.format(ctx.options.board.upper()),
               'PLATFORM_{}=1'.format(platform),
               'MIN_SDK_VERSION={}'.format(env.MIN_SDK_VERSION)]
    env.append_value('DEFINES', defines)

# Build

def configure(ctx):
    pass


def build(ctx):
    pass


# vim:filetype=python
