# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'action_chaining_window.c',
        'alerts.c',
        'alerts_preferences.c',
        'ancs/ancs_filtering.c',
        'ancs/ancs_item.c',
        'ancs/ancs_notifications.c',
        'ancs/ancs_notifications_util.c',
        'ancs/ancs_phone_call.c',
        'ancs/nexmo.c',
        'do_not_disturb.c',
        'do_not_disturb_toggle.c',
        'notification_storage.c',
        'notifications.c',
    ]

    bld.stlib(
        use=['fw_includes', 'services_common_analytics'],
        source=sources,
        target='services_normal_notifications',
    )

    bld.env.SERVICES.append('services_normal_notifications')

    target = bld.path.find_or_declare('services_normal_notifications.pot')
    bld.gettext(source=sources, target=target)
    bld.env.SERVICES_TEXT.append(target)
