# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    conf.recurse('bluetooth')
    conf.recurse('comm_session')


def build(bld):
    bld.recurse('bluetooth')
    bld.recurse('comm_session')

    bld.stlib(
        use=['fw_includes'],
        source=['idle_watchdog.c'],
        target='services_prf_idle_watchdog',
    )
    bld.env.SERVICES.append('services_prf_idle_watchdog')
