# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'vibe_client.c',
        'vibe_intensity.c',
        'vibe_score.c',
        'vibe_score_info.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_normal_vibes',
    )

    bld.env.SERVICES.append('services_normal_vibes')
