/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#define MPU_REGION_APP_BASE_ADDRESS         @APP_BASE_ADDRESS@
#define MPU_REGION_APP_SIZE                 @APP_SIZE@
#define MPU_REGION_APP_DISABLED_SUBREGIONS  @APP_DISABLED_SUBREGIONS@

#define MPU_REGION_WORKER_BASE_ADDRESS         @WORKER_BASE_ADDRESS@
#define MPU_REGION_WORKER_SIZE                 @WORKER_SIZE@
#define MPU_REGION_WORKER_DISABLED_SUBREGIONS  @WORKER_DISABLED_SUBREGIONS@
