# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass

def build(bld):
    if bld.env.MICRO_FAMILY.startswith("NRF"):
        bld.recurse("nrf")
    elif bld.env.MICRO_FAMILY.startswith("SF32LB"):
        bld.recurse("sf32lb")
    elif bld.env.MICRO_FAMILY.startswith("STM32"):
        bld.recurse("stm32")