/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#define DISP_COLS 200
#define DISP_ROWS 228

#define DISPLAY_FRAMEBUFFER_BYTES (DISP_COLS * DISP_ROWS)

#define DISPLAY_ORIENTATION_COLUMN_MAJOR_INVERTED 0
#define DISPLAY_ORIENTATION_ROTATED_180 0
#define DISPLAY_ORIENTATION_ROW_MAJOR 0
#define DISPLAY_ORIENTATION_ROW_MAJOR_INVERTED 1

#define PBL_BW 0
#define PBL_RECT 1

#define PBL_ROUND 0
#define PBL_COLOR 1
