# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'attributes_address.c',
        'contacts.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_normal_contacts',
    )

    bld.env.SERVICES.append('services_normal_contacts')
