def configure(conf):
    conf.recurse('common')
    conf.recurse('normal')
    conf.recurse('prf')

def build(bld):
    bld.env.SERVICES = []
    bld.recurse('common')
    if bld.variant == 'prf':
        bld.recurse('prf')
    else:
        bld.recurse('normal')

    def _build_services(bld, sources):
        bld.gettext(source=sources, target='services.pot')
        use = [
            'fw_includes',
            'freertos_includes',
            'bt_driver',
            'pbl_includes',
        ]

        use.extend(bld.env.SERVICES)

        bld.stlib(source=sources,
                  target='fw_services',
                  use=use)

    def _build_normal_recovery_services(bld):
        def _get_excludes(bld):
            excludes = []

            # Migrated services
            excludes.append('common/analytics/**')
            excludes.append('common/battery/**')
            excludes.append('common/bluetooth/**')
            excludes.append('common/comm_session/**')
            excludes.append('common/compositor/**')
            excludes.append('common/get_bytes/**')
            excludes.append('common/hrm/**')
            excludes.append('common/i18n/**')
            excludes.append('common/new_timer/**')
            excludes.append('common/put_bytes/**')
            excludes.append('common/shared_prf_storage/**')
            excludes.append('common/touch/**')
            excludes.append('normal/activity/**')
            excludes.append('normal/alarms/**')
            excludes.append('normal/app_glances/**')
            excludes.append('normal/app_message/**')
            excludes.append('normal/blob_db/**')
            excludes.append('normal/bluetooth/**')
            excludes.append('normal/comm_session/**')
            excludes.append('normal/contacts/**')
            excludes.append('normal/data_logging/**')
            excludes.append('normal/filesystem/**')
            excludes.append('normal/legacy/**')
            excludes.append('normal/notifications/**')
            excludes.append('normal/process_management/**')
            excludes.append('normal/protobuf_log/**')
            excludes.append('normal/settings/**')
            excludes.append('normal/timeline/**')
            excludes.append('normal/vibes/**')
            excludes.append('normal/voice/**')
            excludes.append('normal/weather/**')
            excludes.append('prf/bluetooth/**')
            excludes.append('prf/comm_session/**')

            if not bld.capability('HAS_MAGNETOMETER'):
                excludes.append('common/ecompass.c')

            return excludes

        excludes = _get_excludes(bld)

        # get common services
        sources = []
        sources.extend(bld.path.ant_glob('common/**/*.c', excl=excludes))

        if bld.variant == 'prf':
            # get recovery services
            sources.extend(bld.path.ant_glob('prf/**/*.c', excl=excludes))
        else:
            # get normal services
            sources.extend(bld.path.ant_glob('normal/**/*.c', excl=excludes))

        if bld.env.QEMU:
            # get qemu services
            sources.extend(bld.path.ant_glob('qemu/**/*.c', excl=excludes))

        sources.extend(bld.path.ant_glob('*.c', excl=excludes))

        # This could really be based on what accel driver is in use
        accel_manager_to_remove = 'legacy/accel_manager.c'
        sources = [x for x in sources if not x.abspath().endswith(accel_manager_to_remove)]

        _build_services(bld, sources)

    if bld.env.VOICE_CODEC_TESTS:
        voice_sample_target = bld.path.get_bld().make_node('normal/voice/voice_test_sample.auto.h')
        bld(features='binary_header',
            source='normal/voice/sample.pcm',
            target=voice_sample_target,
            array_name='s_voice_test_sample')

    _build_normal_recovery_services(bld)


# vim:filetype=python
