def configure(conf):
    conf.recurse('common')
    conf.recurse('normal')
    conf.recurse('prf')

def build(bld):
    bld.env.SERVICES = []
    bld.recurse('common')
    if bld.variant == 'prf':
        bld.recurse('prf')
    else:
        bld.recurse('normal')

    use = ['fw_includes']
    use.extend(bld.env.SERVICES)

    sources = ['services.c']

    bld.stlib(source=sources,
                target='fw_services',
                use=use)

    bld.gettext(source=sources, target='services.pot')

    if bld.env.VOICE_CODEC_TESTS:
        voice_sample_target = bld.path.get_bld().make_node('normal/voice/voice_test_sample.auto.h')
        bld(features='binary_header',
            source='normal/voice/sample.pcm',
            target=voice_sample_target,
            array_name='s_voice_test_sample')

# vim:filetype=python
