#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Generate correctly-rounded reference values for the pow() unit test.

The test exercises pow(2, v) for v = i * 0.001, i in [0, 10000).  Using the
host libm as an oracle makes the expected values host-specific, because glibc
and Apple's libm disagree in the last ULP.  Instead this script computes the
correctly-rounded double for each input ahead of time, using the stdlib
decimal module at high precision, and emits the bit patterns as C.  The table
is therefore identical on every host and the test no longer calls host libm.

For each i:
  * v is the IEEE-754 double nearest i * 0.001, computed exactly as the C test
    computes it (float multiply), so the reference matches the input the test
    actually feeds to pblibc_pow.
  * pow(2, v) is evaluated as exp(v * ln 2) in decimal at 80 significant
    digits, then rounded to the nearest double via float(Decimal), which is
    round-half-to-even, i.e. correct rounding.

Run from the repo root or this directory:
    python3 tests/libc/math/gen_pow_reference.py > tests/libc/math/pow_reference.h
"""

import struct
import sys
from decimal import Decimal, getcontext

# 80 significant digits is far more than the 17 a double needs; the final
# round to double is what fixes the result, the surplus only guards the
# rounding decision near a tie.
getcontext().prec = 80

COUNT = 10000
STEP = 0.001
BASE = 2


def double_to_bits(value: float) -> int:
    """Return the raw 64-bit IEEE-754 representation of a double."""
    return struct.unpack("<Q", struct.pack("<d", value))[0]


def correctly_rounded_pow2(v: float) -> float:
    """Correctly-rounded double for 2 ** v, via exp(v * ln 2) in decimal."""
    ln2 = Decimal(2).ln()
    # Decimal(v) is the exact value of the double v, so no input rounding error
    # is introduced before the transcendental evaluation.
    return float((Decimal(v) * ln2).exp())


def main() -> int:
    rows = []
    for i in range(COUNT):
        v = i * STEP
        expected = correctly_rounded_pow2(v)
        rows.append((double_to_bits(v), double_to_bits(expected)))

    out = sys.stdout
    out.write("/* SPDX-FileCopyrightText: 2026 Core Devices LLC */\n")
    out.write("/* SPDX-License-Identifier: Apache-2.0 */\n\n")
    out.write("/* Generated by gen_pow_reference.py. Do not edit by hand. */\n")
    out.write("/* Correctly-rounded reference for pow(2, i * 0.001), i in "
              "[0, 10000). */\n\n")
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n\n")
    out.write("typedef struct {\n")
    out.write("  uint64_t input_bits;     /* IEEE-754 bits of v = i * 0.001 */\n")
    out.write("  uint64_t expected_bits;  /* IEEE-754 bits of pow(2, v) */\n")
    out.write("} PowReferenceEntry;\n\n")
    out.write(f"#define POW_REFERENCE_COUNT {COUNT}\n\n")
    out.write("static const PowReferenceEntry s_pow_reference[POW_REFERENCE_COUNT] = {\n")
    for input_bits, expected_bits in rows:
        out.write(f"  {{ 0x{input_bits:016x}ull, 0x{expected_bits:016x}ull }},\n")
    out.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
