#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Generate correctly-rounded reference values for the log() unit test.

The test exercises log(v) for v = i * 0.001, i in [1, 10000).  Using the host
libm as an oracle makes the expected values host-specific, because glibc and
Apple's libm disagree in the last ULP.  Instead this script computes the
correctly-rounded double for each input ahead of time, using the stdlib
decimal module at high precision, and emits the bit patterns as C.  The table
is therefore identical on every host and the test no longer calls host libm.

For each i:
  * v is the IEEE-754 double nearest i * 0.001, computed exactly as the C test
    computes it (float multiply), so the reference matches the input the test
    actually feeds to pblibc_log.
  * log(v) is evaluated in decimal at 80 significant digits, then rounded to
    the nearest double via float(Decimal), which is round-half-to-even, i.e.
    correct rounding.

Run from the repo root or this directory:
    python3 tests/libc/math/gen_log_reference.py > tests/libc/math/log_reference.h
"""

import struct
import sys
from decimal import Decimal, getcontext

# 80 significant digits is far more than the 17 a double needs; the final
# round to double is what fixes the result, the surplus only guards the
# rounding decision near a tie.
getcontext().prec = 80

COUNT = 10000  # i in [1, COUNT)
STEP = 0.001


def double_to_bits(value: float) -> int:
    """Return the raw 64-bit IEEE-754 representation of a double."""
    return struct.unpack("<Q", struct.pack("<d", value))[0]


def correctly_rounded_log(v: float) -> float:
    """Correctly-rounded double for the natural log of v, via decimal."""
    # Decimal(v) is the exact value of the double v, so no input rounding error
    # is introduced before the transcendental evaluation.
    return float(Decimal(v).ln())


def main() -> int:
    rows = []
    for i in range(1, COUNT):
        v = i * STEP
        expected = correctly_rounded_log(v)
        rows.append((double_to_bits(v), double_to_bits(expected)))

    out = sys.stdout
    out.write("/* SPDX-FileCopyrightText: 2026 Core Devices LLC */\n")
    out.write("/* SPDX-License-Identifier: Apache-2.0 */\n\n")
    out.write("/* Generated by gen_log_reference.py. Do not edit by hand. */\n")
    out.write(
        "/* Correctly-rounded reference for log(i * 0.001), i in [1, 10000). */\n\n"
    )
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n\n")
    out.write("typedef struct {\n")
    out.write("  uint64_t input_bits;     /* IEEE-754 bits of v = i * 0.001 */\n")
    out.write("  uint64_t expected_bits;  /* IEEE-754 bits of log(v) */\n")
    out.write("} LogReferenceEntry;\n\n")
    out.write(f"#define LOG_REFERENCE_COUNT {len(rows)}\n\n")
    out.write(
        "static const LogReferenceEntry s_log_reference[LOG_REFERENCE_COUNT] = {\n"
    )
    for input_bits, expected_bits in rows:
        out.write(f"  {{ 0x{input_bits:016x}ull, 0x{expected_bits:016x}ull }},\n")
    out.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
