import os
import sys

def configure(conf):
    pass

def build(bld):
    if bld.variant in ('test', 'pdc2png'):
        bld.recurse('pdc2png')

    if bld.variant == 'test':
        bld.recurse('tests')

    # This variant is not supported yet, but can be used to build all tools
    if bld.variant == 'tools':
        # svg2png uses py2app which is macOS-only
        skip = set()
        if sys.platform != 'darwin':
            skip.add(bld.path.find_node('svg2png').abspath())

        tool_dirs = [os.path.dirname(f.abspath()) for f in bld.path.ant_glob('**/wscript')]
        for dir in tool_dirs:
            if dir not in skip:
                bld.recurse(dir)

# vim:filetype=python
