# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'actions_endpoint.c',
        'alarm_layout.c',
        'attribute.c',
        'attribute_group.c',
        'attributes_actions.c',
        'calendar.c',
        'calendar_layout.c',
        'calendar_layout_resources.c',
        'event.c',
        'generic_layout.c',
        'health_layout.c',
        'item.c',
        'layout_layer.c',
        'layout_node.c',
        'metricgroup.c',
        'notification_layout.c',
        'peek.c',
        'reminders.c',
        'sports_layout.c',
        'swap_layer.c',
        'timeline.c',
        'timeline_actions.c',
        'timeline_layout.c',
        'timeline_layout_animations.c',
        'timeline_resources.c',
        'weather_layout.c',
    ]

    bld.stlib(
        use=['fw_includes', 'services_common_analytics'],
        source=sources,
        target='services_normal_timeline',
    )

    bld.env.SERVICES.append('services_normal_timeline')

    target = bld.path.find_or_declare('services_normal_timeline.pot')
    bld.gettext(source=sources, target=target)
    bld.env.SERVICES_TEXT.append(target)
