# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    sources = [
        'new_timer.c',
    ]

    bld.stlib(
        use=['fw_includes'],
        source=sources,
        target='services_common_new_timer',
    )

    bld.env.SERVICES.append('services_common_new_timer')
